### ISSUE TITLE
Add Footer to the website

### ISSUE THREAD

**Issue by Shreedhar03** [Shreedhar03/UrbanCart#2]
- Create an attractive footer for the website
- Use [TailwindCSS](https://tailwindcss.com/) for creating UI
-  Include links to important pages such as **Home**, **Login**, **Sign Up**, **Cart**, **Orders**
- Also add **About Us**, **Contact Us**, **FAQ**, **Terms and Conditions** and **Privacy Policy** in the Footer

- Refer [Dribble](https://dribbble.com/) and [Behance](https://www.behance.net/) for Design

**Comment by Krismahidayat** [comment]
let me handle this

**Comment by Vardhaman619** [comment]
[Check pull request](https://github.com/Shreedhar03/UrbanCart/pull/4)
