### ISSUE TITLE
Add skeleton loader in the frontend

### ISSUE THREAD

**Issue by Shreedhar03** [Shreedhar03/UrbanCart#3]
Add [skeleton loader](https://blog.prototypr.io/skeleton-loader-an-overview-purpose-usage-and-design-173b5340d0e1) for the products card in the `/category/:category` route page
You can use any popular npm package like [react-loading-skeleton](https://www.npmjs.com/package/react-loading-skeleton)

**Comment by Krismahidayat** [comment]
let me handle this

**Comment by Shreedhar03** [comment]
any update ? @Krismahidayat

**Comment by TittoMA** [comment]
can I handle this? @Shreedhar03 
I've created a pull request: https://github.com/Shreedhar03/UrbanCart/pull/5
